name: matrix-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Investigar esta opción
  workflow_dispatch:

# 
jobs:
  matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        node: [10,12]
        exclude:
          - os: windows-latest
            node: 12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: StdOut
        run: echo Matrix owns you!
